import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Page",
  description: "Generated by create next app",
};

type Props = {
  children?: React.ReactNode;
};

export default function HomeLayout({ children }: Props) {
  return (
    <div className="flex flex-col gap-4 min-h-screen items-center justify-center p-24">
      {children}
    </div>
  );
}
